# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: itmaker.banner::lang.size.label

# Model Form Field configuration
form: $/itmaker/banner/models/size/fields.yaml

# Model Class name
modelClass: Itmaker\Banner\Models\Size

# Default redirect location
defaultRedirect: itmaker/banner/sizes

# Create page
create:
    title: itmaker.banner::lang.size.create_title
    redirect: itmaker/banner/sizes/update/:id
    redirectClose: itmaker/banner/sizes

# Update page
update:
    title: itmaker.banner::lang.size.update_title
    redirect: itmaker/banner/sizes
    redirectClose: itmaker/banner/sizes

# Preview page
preview:
    title: itmaker.banner::lang.size.preview_title